services:
  rspamd:
    container_name: rspamd
    image: eilandert/rspamd-git:latest
    restart: always
    ports:
      - 11332:11332
      - 11333:11333
      - 11334:11334
    volumes:
      - ./config/rspamd:/etc/rspamd:rw
      - ./data/rspamd:/var/lib/rspamd
    #    - /coreland:/coreland:rw
    environment:
      - TZ=Europe/Amsterdam
      - SYSLOG_HOST=10.0.0.118

version: "3.8"
