services:
  dovecot:
    container_name: dovecot
    image: eilandert/dovecot-ubuntu:latest
    ports:
      - 24:24/tcp
      - 110:110/tcp
      - 143:143/tcp
      - 993:993/tcp
      - 4190:4190/tcp
    restart: always
    volumes:
      - ./config/dovecot:/etc/dovecot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - TZ=Europe/Amsterdam
#     - SYSLOG_HOST=10.0.0.118
      - DB_DRIVER=mysql
      - DB_DATABASE=vimbadmin
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USERNAME=vimbadmin
      - DB_PASSWORD=secret
version: "3.7"
