# mkdir -p config

services:
  unbound:
    container_name: unbound
    image: eilandert/unbound:latest
    ports:
      - mode: host
        protocol: tcp
        published: 53
        target: 53
      - mode: host
        protocol: udp
        published: 53
        target: 53
    restart: always
    volumes:
      - ./config:/config:rw
    environment:
      - TZ=Europe/Amsterdam

version: "3.7"
