#!/usr/bin/env python3
"""Regenerate .github/dependabot.yml with one docker entry per image directory.

WHY THIS EXISTS
    Every Dockerfile in this repo lives under src/<image>/ — there is none at
    the repo root. Dependabot's `directory:` key does NOT support globs or
    recursion, so a single `directory: "/"` entry silently scans nothing: no
    error, no PRs, no alerts. That is the failure mode this script prevents.
    Each image directory needs its own explicit `updates:` entry, and a new
    image added without one is invisible to Dependabot forever.

USAGE
    tools/gen-dependabot-docker.py [--check] [--dry-run]

    (no flags)  Rewrite .github/dependabot.yml from the tracked Dockerfiles.
    --check     Exit 1 if the file is out of date, print what differs, write
                nothing. Intended for CI — fails when someone adds an image
                without regenerating.
    --dry-run   Print the generated YAML to stdout, write nothing.

INPUTS
    `git ls-files` in the repo root — TRACKED files only, so an untracked
    scratch Dockerfile does not leak into the config. Any path whose basename
    starts with "dockerfile" (case-insensitive) counts, which covers this
    repo's Dockerfile-<variant> naming (Dockerfile-php84-deb etc.). Multiple
    Dockerfiles in one directory collapse to a single entry, which is correct:
    Dependabot scans the directory, not the individual file.

OUTPUTS / SIDE EFFECTS
    Overwrites .github/dependabot.yml in place. No network, no sudo, no git
    writes — inspect with `git diff` and commit yourself.

LIMITS
    Only emits the `docker` ecosystem. If this repo ever grows a composer.json,
    package.json, or .github/workflows/*, those need their own entries — add
    them to EXTRA_UPDATES below rather than hand-editing the generated file,
    or the next run will drop them.

EXTENDING
    - Change cadence/PR cap: edit ENTRY_TEMPLATE.
    - Pin base images by digest instead of tag: that is a Dockerfile change,
      not a config one; Dependabot follows digests once they are in place.
    - Add a non-docker ecosystem: append a literal block to EXTRA_UPDATES.
"""

import argparse
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
CONFIG = REPO / ".github" / "dependabot.yml"

HEADER = """\
# Dependabot version updates.
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# GENERATED by tools/gen-dependabot-docker.py — do not hand-edit; rerun it.
#
# Every Dockerfile in this repo lives under src/<image>/ — there is none at the
# repo root. Dependabot does not glob, so each image directory needs its own
# entry or it is silently never scanned.

version: 2
updates:
"""

ENTRY_TEMPLATE = """
  - package-ecosystem: "docker"
    directory: "{directory}"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      {group}-base-images:
        patterns:
          - "*"
"""

# Literal YAML appended after the generated docker entries. Empty for now; see
# LIMITS in the module docstring before adding to it.
EXTRA_UPDATES = ""


def image_dirs():
    """Directories of every tracked Dockerfile, sorted and deduplicated."""
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.splitlines()
    dirs = {
        line.rsplit("/", 1)[0]
        for line in out
        if "/" in line and line.rsplit("/", 1)[1].lower().startswith("dockerfile")
    }
    return sorted(dirs)


def render(dirs):
    body = "".join(
        ENTRY_TEMPLATE.format(directory=d, group=d.split("/")[-1]) for d in dirs
    )
    return HEADER + body + EXTRA_UPDATES


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if out of date")
    ap.add_argument("--dry-run", action="store_true", help="print, do not write")
    args = ap.parse_args()

    dirs = image_dirs()
    if not dirs:
        sys.exit("no tracked Dockerfiles found — refusing to write an empty config")
    rendered = render(dirs)

    if args.dry_run:
        print(rendered, end="")
        return

    current = CONFIG.read_text() if CONFIG.exists() else ""
    if args.check:
        if current != rendered:
            have = {
                line.split('"')[1]
                for line in current.splitlines()
                if line.strip().startswith("directory:")
            }
            missing, extra = set(dirs) - have, have - set(dirs)
            if missing:
                print("missing entries:", ", ".join(sorted(missing)), file=sys.stderr)
            if extra:
                print("stale entries:", ", ".join(sorted(extra)), file=sys.stderr)
            sys.exit(f"{CONFIG.relative_to(REPO)} is out of date — rerun this script")
        print(f"{CONFIG.relative_to(REPO)} up to date ({len(dirs)} images)")
        return

    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(rendered)
    print(f"wrote {CONFIG.relative_to(REPO)} — {len(dirs)} image directories")


if __name__ == "__main__":
    main()
